import 'react-app-polyfill/ie9';
import './css/index.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import './css/App.css';
import './router';
import '@fortawesome/fontawesome-free/css/all.min.css';
import 'bootstrap-css-only/css/bootstrap.min.css';
import 'mdbreact/dist/css/mdb.css';
import './css/style.css';