<?php
    require 'header.php';
    
    if ($_SERVER['REQUEST_METHOD'] === 'GET') {
        $array = array(
            array( value => "AK", text => "Alaska"),
            array( value => "AL", text => "Alabama"),
            array( value => "AR", text => "Arkansas" ),
            array( value => "AS", text => "American Samoa" ),
            array( value => "AZ", text => "Arizona" ),
            array( value => "CA", text => "California" ),
            array( value => "CO", text => "Colorado" ),
            array( value => "CT", text => "Connecticut" ),
            array( value => "DC", text => "District of Columbia" ),
            array( value => "DE", text => "Delaware" ),
            array( value => "FL", text => "Florida" ),
            array( value => "GA", text => "Georgia" ),
            array( value => "GU", text => "Guam" ),
            array( value => "HI", text => "Hawaii" ),
            array( value => "IA", text => "Iowa" ),
            array( value => "ID", text => "Idaho" ),
            array( value => "IL", text => "Illinois" ),
            array( value => "IN", text => "Indiana" ),
            array( value => "KS", text => "Kansas" ),
            array( value => "KY", text => "Kentucky" ),
            array( value => "LA", text => "Louisiana" ),
            array( value => "MA", text => "Massachusetts" ),
            array( value => "MD", text => "Maryland" ),
            array( value => "ME", text => "Maine" ),
            array( value => "MI", text => "Michigan" ),
            array( value => "MN", text => "Minnesota" ),
            array( value => "MO", text => "Missouri" ),
            array( value => "MS", text => "Mississippi" ),
            array( value => "MT", text => "Montana" ),
            array( value => "NC", text => "North Carolina" ),
            array( value => "ND", text => "North Dakota" ),
            array( value => "NE", text => "Nebraska" ),
            array( value => "NH", text => "New Hampshire" ),
            array( value => "NJ", text => "New Jersey" ),
            array( value => "NM", text => "New Mexico" ),
            array( value => "NV", text => "Nevada" ),
            array( value => "NY", text => "New York" ),
            array( value => "OH", text => "Ohio" ),
            array( value => "OK", text => "Oklahoma" ),
            array( value => "OR", text => "Oregon" ),
            array( value => "PA", text => "Pennsylvania" ),
            array( value => "PR", text => "Puerto Rico" ),
            array( value => "RI", text => "Rhode Island" ),
            array( value => "SC", text => "South Carolina" ),
            array( value => "SD", text => "South Dakota" ),
            array( value => "TN", text => "Tennessee" ),
            array( value => "TX", text => "Texas" ),
            array( value => "UT", text => "Utah" ),
            array( value => "VA", text => "Virginia" ),
            array( value => "VI", text => "Virgin Islands" ),
            array( value => "VT", text => "Vermont" ),
            array( value => "WA", text => "Washington" ),
            array( value => "WI", text => "Wisconsin" ),
            array( value => "WV", text => "West Virginia" ),
            array( value => "WY", text => "Wyoming" )
        );
        echo json_encode($array);
    }
?>
